npcs=blacksmith,darius,farmer

npc.blacksmith.displayName=Blacksmith
npc.blacksmith.category=specialist
npc.blacksmith.runRescueRole=Blacksmith_Escort_Objective
npc.blacksmith.hubRole=Blacksmith_Escort_Base
npc.blacksmith.plotType=blacksmith
npc.blacksmith.homeTemplateId=blacksmith_tier1
npc.blacksmith.prePlotQuestId=retrieve_blacksmith_tools
npc.blacksmith.plotUnlockMode=materials
npc.blacksmith.services=trade,quests,upgrades
npc.blacksmith.defaultCraftUnlocks=iron_sword
npc.blacksmith.defaultTradeUnlocks=crude_dagger,iron_dagger,crude_sword,iron_sword,scrap_sword,crude_axe,iron_axe,crude_bow,iron_bow,crude_mace,iron_mace,scrap_mace,scrap_shield,iron_shield,crude_arrow,copper_helm,copper_chest,copper_gloves,copper_boots,iron_helm,iron_chest,iron_gloves,iron_boots,thorium_dagger,cobalt_dagger,thorium_sword,cobalt_sword,thorium_axe,cobalt_axe,thorium_bow,cobalt_bow,thorium_mace,cobalt_mace,thorium_shield,cobalt_shield,iron_crossbow,thorium_helm,thorium_chest,thorium_gloves,thorium_boots,cobalt_helm,cobalt_chest,cobalt_gloves,cobalt_boots,adamantite_dagger,adamantite_sword,adamantite_axe,adamantite_bow,adamantite_mace,adamantite_shield,adamantite_helm,adamantite_chest,adamantite_gloves,adamantite_boots
npc.blacksmith.followStateAliases=follow,$interaction

npc.darius.displayName=Captain Darius
npc.darius.category=specialist
npc.darius.hubRole=Captain_Darius_Hub
npc.darius.plotUnlockMode=none
npc.darius.services=talk,quests
npc.darius.defaultCraftUnlocks=
npc.darius.defaultTradeUnlocks=
npc.darius.alwaysInHub=true
npc.darius.hubSpawn.x=557.316650390625
npc.darius.hubSpawn.y=180.0
npc.darius.hubSpawn.z=73.4477310180664
npc.darius.hubSpawn.pitch=0.0
npc.darius.hubSpawn.yaw=-5.447013
npc.darius.hubSpawn.roll=0.0

npc.farmer.displayName=Farmer
npc.farmer.category=specialist
npc.farmer.runRescueRole=Farmer_Escort_Objective
npc.farmer.hubRole=Farmer_Base
npc.farmer.plotType=farmer
npc.farmer.homeTemplateId=farmer_tier1
npc.farmer.plotUnlockMode=materials
npc.farmer.services=talk,quests,upgrades
npc.farmer.defaultCraftUnlocks=
npc.farmer.defaultTradeUnlocks=
npc.farmer.followStateAliases=follow,$interaction
npc.farmer.hubSpawn.x=569.0
npc.farmer.hubSpawn.y=182.0
npc.farmer.hubSpawn.z=34.0
npc.farmer.hubSpawn.pitch=0.0
npc.farmer.hubSpawn.yaw=180.0
npc.farmer.hubSpawn.roll=0.0
