npc.key=pack_goat
npc.displayName=Pack Goat
npc.readyDialogueText=Baa.
npc.noWorkshopDialogueText=Baa.
npc.category=animal
npc.hubRole=PackGoat_Base
npc.plotUnlockMode=none
npc.services=
npc.defaultCraftUnlocks=
npc.defaultTradeUnlocks=
npc.animal.routeToFarmer=true
npc.animal.farmerNpcKey=farmer

offers=
upgrades=
